version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/static/faces:/app/frontend/static/faces
      - ./frontend/static/face_recognition_model.pkl:/app/frontend/static/face_recognition_model.pkl
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ujjwalsql@2500
      MYSQL_DATABASE: Test1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: